aws:
  region: us-east-1
  s3:
    bucket: mycdn-origin

cloudfront:
  domain: d4kivs27yfm73.cloudfront.net

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8080
  tomcat:
    max-http-form-post-size: 52428800  